"""seed lever / ashby / workable companies, broaden companies.slug uniqueness

Two related changes in one migration:

1. Drop the global UNIQUE on ``companies.slug`` and replace it with a
   composite UNIQUE on ``(slug, source)``. The original constraint
   assumed every slug was globally unique, which breaks the moment
   ``linear`` exists on both Greenhouse and Ashby. The composite is the
   correct identity for an ATS-hosted company row.

2. Insert a small starter allowlist for the new ATS families so the
   scheduler has something to ingest the first time it ticks against any
   of them. Existing greenhouse rows are untouched. Inserts are guarded
   by ``ON CONFLICT (slug, source) DO NOTHING`` so re-running the
   migration (in tests, or on a partially-populated DB) is a no-op.

Revision ID: 0012_seed_lever_ashby_workable
Revises: 0011_application_verify
"""
from alembic import op


revision = "0012_seed_lever_ashby_workable"
down_revision = "0011_application_verify"
branch_labels = None
depends_on = None


# Starter allowlist per source. Slugs verified against the public ATS
# endpoints at the time of writing; a 404 at runtime is non-fatal (the
# adapter normalizes to []). Greenhouse rows used to be seeded at worker
# boot from a hardcoded constant — they're now folded into this migration
# so the DB is the single source of truth for the allowlist.
_NEW_COMPANIES: list[tuple[str, str, str]] = [
    # (source, slug, display_name)
    # Greenhouse — moved from app/services/sources/greenhouse_companies.py.
    ("greenhouse", "anthropic", "Anthropic"),
    ("greenhouse", "openai", "OpenAI"),
    ("greenhouse", "stripe", "Stripe"),
    ("greenhouse", "vercel", "Vercel"),
    ("greenhouse", "linear", "Linear"),
    ("greenhouse", "airbnb", "Airbnb"),
    ("greenhouse", "databricks", "Databricks"),
    ("greenhouse", "ramp", "Ramp"),
    # Lever.
    ("lever", "netflix", "Netflix"),
    ("lever", "palantir", "Palantir"),
    # Ashby. ``linear`` collides with the Greenhouse row by slug only —
    # the new (slug, source) UNIQUE introduced in this migration is what
    # makes the second insert legal.
    ("ashby", "notion", "Notion"),
    ("ashby", "linear", "Linear"),
    # Workable.
    ("workable", "miro", "Miro"),
    ("workable", "gettyimages", "Getty Images"),
]


def upgrade() -> None:
    # 1. Broaden the slug UNIQUE constraint. The original (created in 0009)
    #    is autogenerated as ``companies_slug_key`` by Postgres.
    op.drop_constraint("companies_slug_key", "companies", type_="unique")
    op.create_unique_constraint(
        "uq_companies_slug_source", "companies", ["slug", "source"]
    )

    # 2. Seed the new (source, slug) rows. Use raw SQL with a parameter
    #    list — Alembic's bulk_insert doesn't support ON CONFLICT.
    for source, slug, display in _NEW_COMPANIES:
        op.execute(
            f"""
            INSERT INTO companies (slug, display_name, source, enabled)
            VALUES ('{slug}', '{display.replace("'", "''")}', '{source}', true)
            ON CONFLICT (slug, source) DO NOTHING
            """
        )


def downgrade() -> None:
    # Best-effort row removal first so the original UNIQUE can be restored
    # without conflict.
    for source, slug, _display in _NEW_COMPANIES:
        op.execute(
            f"DELETE FROM companies WHERE slug='{slug}' AND source='{source}'"
        )
    op.drop_constraint(
        "uq_companies_slug_source", "companies", type_="unique"
    )
    op.create_unique_constraint("companies_slug_key", "companies", ["slug"])
